export const AUDIT_OPERATION_LABEL: Record<string, string> = {
  create: "Criação",
  update: "Atualização",
  delete: "Remoção",
};

export const AUDIT_RESOURCE_LABEL: Record<string, string> = {
  login: "Usuários",
  admin: "Administração",
  medicamentos: "Medicamentos",
  insumos: "Insumos",
  residentes: "Residentes",
  estoque: "Estoque",
  movimentacoes: "Movimentações",
  armarios: "Armários",
  gavetas: "Gavetas",
  "categoria-armario": "Categoria de armário",
  "categoria-gaveta": "Categoria de gaveta",
  dashboard: "Dashboard",
  relatorios: "Relatórios",
};

export const FRONTEND_TO_BACKEND_KEY: Record<string, string> = {
  firstName: "first_name",
  lastName: "last_name",
  name: "nome",
  casela: "num_casela",
  createdAt: "created_at",
  updatedAt: "updated_at",
};

export const AUDIT_FIELD_LABEL: Record<string, string> = {
  first_name: "Nome",
  last_name: "Sobrenome",
  login: "Login",
  role: "Privilégio",
  permissions: "Permissões",
  created_at: "Criado em",
  updated_at: "Atualizado em",
  num_casela: "Casela",
  nome: "Nome",
  dosagem: "Dosagem",
  principio_ativo: "Princípio ativo",
  unidade_medida: "Unidade de medida",
  estoque_minimo: "Estoque mínimo",
  descricao: "Descrição",
  numero: "Número",
  num_armario: "Número do armário",
  num_gaveta: "Número da gaveta",
  categoria_id: "ID da categoria",
  armario_id: "Armário",
  gaveta_id: "Gaveta",
  casela_id: "Casela",
  medicamento_id: "Medicamento",
  insumo_id: "Insumo",
  medicamento_nome: "Medicamento",
  insumo_nome: "Insumo",
  quantidade: "Quantidade",
  validade: "Validade",
  setor: "Setor",
  lote: "Lote",
  origem: "Origem",
  tipo: "Tipo",
  observacao: "Observação",
  dias_para_repor: "Dias para repor",
  destino: "Destino",
  status: "Status",
  preco: "Preço",
  suspended_at: "Suspenso em",
  ultima_reposicao: "Última reposição",
};

export const REPORT_OPTIONS = [
  { value: "insumos", label: "Insumos" },
  { value: "medicamentos", label: "Medicamentos" },
  { value: "residentes", label: "Residentes" },
  { value: "psicotropicos", label: "Psicotrópicos" },
  { value: "insumos_medicamentos", label: "Insumos e Medicamentos" },
  { value: "residente_consumo", label: "Consumo por Residente" },
  { value: "transferencias", label: "Transferências" },
  { value: "movimentacoes", label: "Movimentações" },
  { value: "medicamentos_residente", label: "Medicamentos por Residente" },
  { value: "medicamentos_vencidos", label: "Medicamentos Vencidos" },
  { value: "expiringSoon", label: "Próximos ao Vencimento" },
];
